name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.10
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  go_router: ^14.1.4
  go_router_builder: ^2.7.0
  intersperse: ^2.0.0
  intl: ^0.19.0
  listenable_stream: ^1.1.0
  pausable_timer: ^3.1.0+3
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceSans3-SemiBold.ttf
          weight: 600
          